/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    lists: List;
    items: Item;
    categories: Category;
    users: User;
    media: Media;
    entries: Entry;
    redirects: Redirect;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    lists: {
      entries: 'entries';
    };
    items: {
      appearsIn: 'entries';
    };
  };
  collectionsSelect: {
    lists: ListsSelect<false> | ListsSelect<true>;
    items: ItemsSelect<false> | ItemsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    entries: EntriesSelect<false> | EntriesSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('vi' | 'en') | ('vi' | 'en')[];
  globals: {};
  globalsSelect: {};
  locale: 'vi' | 'en';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lists".
 */
export interface List {
  id: number;
  title: string;
  intro?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Một câu ngắn hiện ở đầu bảng, ví dụ: "Vote phim Việt bạn thấy hay nhất · không tính phim ra rạp dưới 30 ngày".
   */
  rules?: string | null;
  /**
   * Dùng khi đếm số mục, ví dụ "120 phim", "38 quán".
   */
  itemNoun?: string | null;
  entries?: {
    docs?: (number | Entry)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  /**
   * Để trống thì dùng ảnh ghép từ các mục đứng đầu bảng.
   */
  coverImage?: (number | null) | Media;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  confirmUrlChange?: boolean | null;
  /**
   * Tự tính từ slug.
   */
  url?: string | null;
  category: number | Category;
  listType: 'permanent' | 'event';
  startsAt?: string | null;
  endsAt?: string | null;
  /**
   * Khi có tính năng vote, thứ hạng sẽ do vote quyết định.
   */
  rankingMode: 'manual' | 'votes';
  author?: (number | null) | User;
  createdBy?: (number | null) | User;
  updatedBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "entries".
 */
export interface Entry {
  id: number;
  _entries_entries_order?: string | null;
  list: number | List;
  /**
   * Chọn mục có sẵn, hoặc bấm + để tạo mục mới ngay tại đây.
   */
  item: number | Item;
  itemName?: string | null;
  /**
   * Vì sao mục này có mặt trong bảng này (khác với mô tả chung của mục). Ví dụ trong bảng "chụp ảnh đẹp" thì nói về camera.
   */
  blurb?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  createdBy?: (number | null) | User;
  updatedBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "items".
 */
export interface Item {
  id: number;
  name: string;
  /**
   * 1–2 câu, dùng cho thẻ, dòng phụ trong bảng và mô tả SEO mặc định (tối đa 300 ký tự).
   */
  summary?: string | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  attributes?:
    (ProductAttributes | PlaceAttributes | CreativeWorkAttributes | PersonAttributes | OrganizationAttributes)[] | null;
  /**
   * Ví dụ: "Doanh thu" – "hơn 400 tỷ đồng", "Pin" – "5.000 mAh".
   */
  facts?:
    | {
        label: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Ảnh đại diện của mục (thumbnail trong bảng, ảnh chia sẻ).
   */
  image?: (number | null) | Media;
  gallery?:
    | {
        kind?: ('image' | 'video') | null;
        image?: (number | null) | Media;
        videoUrl?: string | null;
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  confirmUrlChange?: boolean | null;
  /**
   * Nhóm lớn của chuyên mục quyết định URL: /review (Sản phẩm & Dịch vụ) hoặc /wiki (Thông tin).
   */
  category: number | Category;
  /**
   * Tự tính từ slug và chuyên mục.
   */
  url?: string | null;
  /**
   * Thêm hoặc gỡ mục khỏi bảng trong màn hình sửa bảng (tab "Các mục").
   */
  appearsIn?: {
    docs?: (number | Entry)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  createdBy?: (number | null) | User;
  updatedBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ProductAttributes".
 */
export interface ProductAttributes {
  brand?: string | null;
  model?: string | null;
  price?: number | null;
  releaseDate?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'product';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PlaceAttributes".
 */
export interface PlaceAttributes {
  address?: string | null;
  district?: string | null;
  city?: string | null;
  priceRange?: ('budget' | 'moderate' | 'upscale' | 'luxury') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'place';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CreativeWorkAttributes".
 */
export interface CreativeWorkAttributes {
  workType?: ('movie' | 'series' | 'book' | 'song' | 'album' | 'game' | 'show') | null;
  year?: number | null;
  creators?: string | null;
  cast?: string | null;
  genres?: string | null;
  durationMinutes?: number | null;
  releaseDate?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'creativeWork';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PersonAttributes".
 */
export interface PersonAttributes {
  birthYear?: number | null;
  profession?: string | null;
  hometown?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'person';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "OrganizationAttributes".
 */
export interface OrganizationAttributes {
  foundedYear?: number | null;
  headquarters?: string | null;
  website?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'organization';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Mô tả nội dung ảnh (bắt buộc). Ví dụ: "Poster phim Mắt Biếc (2019)".
   */
  alt: string;
  caption?: string | null;
  /**
   * Hiện dưới ảnh, ví dụ: "Galaxy Studio".
   */
  credit?: string | null;
  createdBy?: (number | null) | User;
  updatedBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumb?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  displayName: string;
  avatar?: (number | null) | Media;
  role?: ('admin' | 'editor') | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Ba tầng: Nhóm lớn › Chuyên mục › Chuyên mục con. Chỉ Admin được tạo, di chuyển, đổi slug hoặc xóa chuyên mục.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  _order?: string | null;
  name: string;
  /**
   * Hiện ở banner đầu trang chuyên mục (1–2 câu).
   */
  description?: string | null;
  about?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  faq?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  meta?: {
    title?: string | null;
    description?: string | null;
  };
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  confirmUrlChange?: boolean | null;
  /**
   * Để trống nếu đây là nhóm lớn.
   */
  parent?: (number | null) | Category;
  /**
   * Chỉ đặt ở nhóm lớn, không đổi được sau khi tạo. Chuyên mục con kế thừa.
   */
  itemRoute?: ('review' | 'wiki') | null;
  /**
   * Tự tính từ slug và chuyên mục cha.
   */
  path?: string | null;
  /**
   * 0 = nhóm lớn, 1 = chuyên mục, 2 = chuyên mục con.
   */
  level?: number | null;
  group?: (number | null) | Category;
  icon?: string | null;
  color?: ('tech' | 'food' | 'beauty' | 'finance' | 'travel' | 'film' | 'music' | 'education') | null;
  breadcrumbs?:
    | {
        doc?: (number | null) | Category;
        url?: string | null;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  createdBy?: (number | null) | User;
  updatedBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * Redirect 301 tự tạo khi URL công khai của nội dung đã đăng thay đổi.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: number;
  from: string;
  to?: {
    type?: ('reference' | 'custom') | null;
    reference?:
      | ({
          relationTo: 'lists';
          value: number | List;
        } | null)
      | ({
          relationTo: 'items';
          value: number | Item;
        } | null)
      | ({
          relationTo: 'categories';
          value: number | Category;
        } | null);
    url?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'lists';
        value: number | List;
      } | null)
    | ({
        relationTo: 'items';
        value: number | Item;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'entries';
        value: number | Entry;
      } | null)
    | ({
        relationTo: 'redirects';
        value: number | Redirect;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lists_select".
 */
export interface ListsSelect<T extends boolean = true> {
  title?: T;
  intro?: T;
  rules?: T;
  itemNoun?: T;
  entries?: T;
  coverImage?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  generateSlug?: T;
  slug?: T;
  confirmUrlChange?: T;
  url?: T;
  category?: T;
  listType?: T;
  startsAt?: T;
  endsAt?: T;
  rankingMode?: T;
  author?: T;
  createdBy?: T;
  updatedBy?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "items_select".
 */
export interface ItemsSelect<T extends boolean = true> {
  name?: T;
  summary?: T;
  description?: T;
  attributes?:
    | T
    | {
        product?: T | ProductAttributesSelect<T>;
        place?: T | PlaceAttributesSelect<T>;
        creativeWork?: T | CreativeWorkAttributesSelect<T>;
        person?: T | PersonAttributesSelect<T>;
        organization?: T | OrganizationAttributesSelect<T>;
      };
  facts?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  image?: T;
  gallery?:
    | T
    | {
        kind?: T;
        image?: T;
        videoUrl?: T;
        caption?: T;
        id?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  generateSlug?: T;
  slug?: T;
  confirmUrlChange?: T;
  category?: T;
  url?: T;
  appearsIn?: T;
  createdBy?: T;
  updatedBy?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ProductAttributes_select".
 */
export interface ProductAttributesSelect<T extends boolean = true> {
  brand?: T;
  model?: T;
  price?: T;
  releaseDate?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PlaceAttributes_select".
 */
export interface PlaceAttributesSelect<T extends boolean = true> {
  address?: T;
  district?: T;
  city?: T;
  priceRange?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CreativeWorkAttributes_select".
 */
export interface CreativeWorkAttributesSelect<T extends boolean = true> {
  workType?: T;
  year?: T;
  creators?: T;
  cast?: T;
  genres?: T;
  durationMinutes?: T;
  releaseDate?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PersonAttributes_select".
 */
export interface PersonAttributesSelect<T extends boolean = true> {
  birthYear?: T;
  profession?: T;
  hometown?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "OrganizationAttributes_select".
 */
export interface OrganizationAttributesSelect<T extends boolean = true> {
  foundedYear?: T;
  headquarters?: T;
  website?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  _order?: T;
  name?: T;
  description?: T;
  about?: T;
  faq?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
      };
  generateSlug?: T;
  slug?: T;
  confirmUrlChange?: T;
  parent?: T;
  itemRoute?: T;
  path?: T;
  level?: T;
  group?: T;
  icon?: T;
  color?: T;
  breadcrumbs?:
    | T
    | {
        doc?: T;
        url?: T;
        label?: T;
        id?: T;
      };
  createdBy?: T;
  updatedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  displayName?: T;
  avatar?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  credit?: T;
  createdBy?: T;
  updatedBy?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumb?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "entries_select".
 */
export interface EntriesSelect<T extends boolean = true> {
  _entries_entries_order?: T;
  list?: T;
  item?: T;
  itemName?: T;
  blurb?: T;
  createdBy?: T;
  updatedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  from?: T;
  to?:
    | T
    | {
        type?: T;
        reference?: T;
        url?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}